# Generated by Django 4.2.6 on 2023-11-01 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(related_name='item_carts', to='item.item')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
