# Generated by Django 4.2.6 on 2023-11-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
