# Generated by Django 4.2.6 on 2023-11-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantity',
            new_name='stocks',
        ),
    ]
