# Generated by Django 4.2.6 on 2023-11-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_rename_quantity_item_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
