# Generated by Django 4.2.6 on 2023-11-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_remove_cart_items_cart_total_price_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
