# Generated by Django 4.2.6 on 2023-11-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_item_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='amount',
            new_name='quantity_sold',
        ),
    ]
