# Generated by Django 4.2.6 on 2023-12-14 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0010_rename_amount_item_quantity_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
