# Generated by Django 4.2.6 on 2023-12-14 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0011_item_favorited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='favorited_by',
        ),
        migrations.AddField(
            model_name='item',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
