# Generated by Django 4.2.6 on 2023-11-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_checkoutinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('total_price', models.FloatField()),
                ('delivery_first_name', models.CharField(max_length=100)),
                ('delivery_last_name', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='CheckoutInfo',
        ),
    ]
