# Generated by Django 4.2.6 on 2023-11-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_deliveryinformation_delete_frontendorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_info',
        ),
    ]
