# Generated by Django 4.2.6 on 2023-11-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_quantity'),
        ('cart', '0002_remove_cart_items_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='carts', to='item.item'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
